### ISSUE TITLE
Elasticsearch v2.x compatibility

### ISSUE THREAD

**Issue by wawrzyn** [jprante/elasticsearch-functionscore-conditionalboost#1]
Are you planning to provide a version of this plugin that works with ES2.x as well?

**Comment by jprante** [comment]
Yes, I hope I find time in the next weeks.

**Comment by jprante** [comment]
It was easier than I thought. I just released plugin version 2.3.3.0 for Elasticsearch 2.3.3

**Comment by wawrzyn** [comment]
That was quick - Thank you ! You made my day
