### ISSUE TITLE
Using conditionalboost for null or empty string check

### ISSUE THREAD

**Issue by tdicken73** [jprante/elasticsearch-functionscore-conditionalboost#3]
I'd like to write a function score that is able to negatively boost ("value" : "0.5") hits that don't have specific fields that should be required to output. Is it possible to do this using conditionalboost?The fields will either be empty strings like, "", or field value will be null.

**Comment by jprante** [comment]
I doubt it works with the existing code, it looks for terms in the index to boost. 

Maybe you can use `missing` in https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-field-value-factor
